/* 
 * Xero Assets API
 *
 * This is the Xero Assets API
 *
 * The version of the OpenAPI document: 2.8.2
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Xero.NetStandard.OAuth2.Api;
using Xero.NetStandard.OAuth2.Model.Asset;
using Xero.NetStandard.OAuth2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Xero.NetStandard.OAuth2.Test.Model.Asset
{
    /// <summary>
    ///  Class for testing Asset
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AssetTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Asset
        //private Asset instance;

        public AssetTests()
        {
            // TODO uncomment below to create an instance of Asset
            //instance = new Asset();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Asset
        /// </summary>
        [Fact]
        public void AssetInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Asset
            //Assert.IsInstanceOfType<Asset> (instance, "variable 'instance' is a Asset");
        }


        /// <summary>
        /// Test the property 'AssetId'
        /// </summary>
        [Fact]
        public void AssetIdTest()
        {
            // TODO unit test for the property 'AssetId'
        }
        /// <summary>
        /// Test the property 'AssetName'
        /// </summary>
        [Fact]
        public void AssetNameTest()
        {
            // TODO unit test for the property 'AssetName'
        }
        /// <summary>
        /// Test the property 'AssetTypeId'
        /// </summary>
        [Fact]
        public void AssetTypeIdTest()
        {
            // TODO unit test for the property 'AssetTypeId'
        }
        /// <summary>
        /// Test the property 'AssetNumber'
        /// </summary>
        [Fact]
        public void AssetNumberTest()
        {
            // TODO unit test for the property 'AssetNumber'
        }
        /// <summary>
        /// Test the property 'PurchaseDate'
        /// </summary>
        [Fact]
        public void PurchaseDateTest()
        {
            // TODO unit test for the property 'PurchaseDate'
        }
        /// <summary>
        /// Test the property 'PurchasePrice'
        /// </summary>
        [Fact]
        public void PurchasePriceTest()
        {
            // TODO unit test for the property 'PurchasePrice'
        }
        /// <summary>
        /// Test the property 'DisposalDate'
        /// </summary>
        [Fact]
        public void DisposalDateTest()
        {
            // TODO unit test for the property 'DisposalDate'
        }
        /// <summary>
        /// Test the property 'DisposalPrice'
        /// </summary>
        [Fact]
        public void DisposalPriceTest()
        {
            // TODO unit test for the property 'DisposalPrice'
        }
        /// <summary>
        /// Test the property 'AssetStatus'
        /// </summary>
        [Fact]
        public void AssetStatusTest()
        {
            // TODO unit test for the property 'AssetStatus'
        }
        /// <summary>
        /// Test the property 'WarrantyExpiryDate'
        /// </summary>
        [Fact]
        public void WarrantyExpiryDateTest()
        {
            // TODO unit test for the property 'WarrantyExpiryDate'
        }
        /// <summary>
        /// Test the property 'SerialNumber'
        /// </summary>
        [Fact]
        public void SerialNumberTest()
        {
            // TODO unit test for the property 'SerialNumber'
        }
        /// <summary>
        /// Test the property 'BookDepreciationSetting'
        /// </summary>
        [Fact]
        public void BookDepreciationSettingTest()
        {
            // TODO unit test for the property 'BookDepreciationSetting'
        }
        /// <summary>
        /// Test the property 'BookDepreciationDetail'
        /// </summary>
        [Fact]
        public void BookDepreciationDetailTest()
        {
            // TODO unit test for the property 'BookDepreciationDetail'
        }
        /// <summary>
        /// Test the property 'CanRollback'
        /// </summary>
        [Fact]
        public void CanRollbackTest()
        {
            // TODO unit test for the property 'CanRollback'
        }
        /// <summary>
        /// Test the property 'AccountingBookValue'
        /// </summary>
        [Fact]
        public void AccountingBookValueTest()
        {
            // TODO unit test for the property 'AccountingBookValue'
        }
        /// <summary>
        /// Test the property 'IsDeleteEnabledForDate'
        /// </summary>
        [Fact]
        public void IsDeleteEnabledForDateTest()
        {
            // TODO unit test for the property 'IsDeleteEnabledForDate'
        }

    }

}
