/* 
 * Xero Assets API
 *
 * This is the Xero Assets API
 *
 * The version of the OpenAPI document: 2.8.2
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Xero.NetStandard.OAuth2.Api;
using Xero.NetStandard.OAuth2.Model.Asset;
using Xero.NetStandard.OAuth2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Xero.NetStandard.OAuth2.Test.Model.Asset
{
    /// <summary>
    ///  Class for testing AssetStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AssetStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AssetStatus
        //private AssetStatus instance;

        public AssetStatusTests()
        {
            // TODO uncomment below to create an instance of AssetStatus
            //instance = new AssetStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AssetStatus
        /// </summary>
        [Fact]
        public void AssetStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AssetStatus
            //Assert.IsInstanceOfType<AssetStatus> (instance, "variable 'instance' is a AssetStatus");
        }



    }

}
