/* 
 * Xero Assets API
 *
 * This is the Xero Assets API
 *
 * The version of the OpenAPI document: 2.8.2
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Xero.NetStandard.OAuth2.Api;
using Xero.NetStandard.OAuth2.Model.Asset;
using Xero.NetStandard.OAuth2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Xero.NetStandard.OAuth2.Test.Model.Asset
{
    /// <summary>
    ///  Class for testing AssetType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AssetTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AssetType
        //private AssetType instance;

        public AssetTypeTests()
        {
            // TODO uncomment below to create an instance of AssetType
            //instance = new AssetType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AssetType
        /// </summary>
        [Fact]
        public void AssetTypeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AssetType
            //Assert.IsInstanceOfType<AssetType> (instance, "variable 'instance' is a AssetType");
        }


        /// <summary>
        /// Test the property 'AssetTypeId'
        /// </summary>
        [Fact]
        public void AssetTypeIdTest()
        {
            // TODO unit test for the property 'AssetTypeId'
        }
        /// <summary>
        /// Test the property 'AssetTypeName'
        /// </summary>
        [Fact]
        public void AssetTypeNameTest()
        {
            // TODO unit test for the property 'AssetTypeName'
        }
        /// <summary>
        /// Test the property 'FixedAssetAccountId'
        /// </summary>
        [Fact]
        public void FixedAssetAccountIdTest()
        {
            // TODO unit test for the property 'FixedAssetAccountId'
        }
        /// <summary>
        /// Test the property 'DepreciationExpenseAccountId'
        /// </summary>
        [Fact]
        public void DepreciationExpenseAccountIdTest()
        {
            // TODO unit test for the property 'DepreciationExpenseAccountId'
        }
        /// <summary>
        /// Test the property 'AccumulatedDepreciationAccountId'
        /// </summary>
        [Fact]
        public void AccumulatedDepreciationAccountIdTest()
        {
            // TODO unit test for the property 'AccumulatedDepreciationAccountId'
        }
        /// <summary>
        /// Test the property 'BookDepreciationSetting'
        /// </summary>
        [Fact]
        public void BookDepreciationSettingTest()
        {
            // TODO unit test for the property 'BookDepreciationSetting'
        }
        /// <summary>
        /// Test the property 'Locks'
        /// </summary>
        [Fact]
        public void LocksTest()
        {
            // TODO unit test for the property 'Locks'
        }

    }

}
