/* 
 * Xero Assets API
 *
 * This is the Xero Assets API
 *
 * The version of the OpenAPI document: 2.8.2
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Xero.NetStandard.OAuth2.Api;
using Xero.NetStandard.OAuth2.Model.Asset;
using Xero.NetStandard.OAuth2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Xero.NetStandard.OAuth2.Test.Model.Asset
{
    /// <summary>
    ///  Class for testing BookDepreciationSetting
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BookDepreciationSettingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BookDepreciationSetting
        //private BookDepreciationSetting instance;

        public BookDepreciationSettingTests()
        {
            // TODO uncomment below to create an instance of BookDepreciationSetting
            //instance = new BookDepreciationSetting();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BookDepreciationSetting
        /// </summary>
        [Fact]
        public void BookDepreciationSettingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BookDepreciationSetting
            //Assert.IsInstanceOfType<BookDepreciationSetting> (instance, "variable 'instance' is a BookDepreciationSetting");
        }


        /// <summary>
        /// Test the property 'DepreciationMethod'
        /// </summary>
        [Fact]
        public void DepreciationMethodTest()
        {
            // TODO unit test for the property 'DepreciationMethod'
        }
        /// <summary>
        /// Test the property 'AveragingMethod'
        /// </summary>
        [Fact]
        public void AveragingMethodTest()
        {
            // TODO unit test for the property 'AveragingMethod'
        }
        /// <summary>
        /// Test the property 'DepreciationRate'
        /// </summary>
        [Fact]
        public void DepreciationRateTest()
        {
            // TODO unit test for the property 'DepreciationRate'
        }
        /// <summary>
        /// Test the property 'EffectiveLifeYears'
        /// </summary>
        [Fact]
        public void EffectiveLifeYearsTest()
        {
            // TODO unit test for the property 'EffectiveLifeYears'
        }
        /// <summary>
        /// Test the property 'DepreciationCalculationMethod'
        /// </summary>
        [Fact]
        public void DepreciationCalculationMethodTest()
        {
            // TODO unit test for the property 'DepreciationCalculationMethod'
        }
        /// <summary>
        /// Test the property 'DepreciableObjectId'
        /// </summary>
        [Fact]
        public void DepreciableObjectIdTest()
        {
            // TODO unit test for the property 'DepreciableObjectId'
        }
        /// <summary>
        /// Test the property 'DepreciableObjectType'
        /// </summary>
        [Fact]
        public void DepreciableObjectTypeTest()
        {
            // TODO unit test for the property 'DepreciableObjectType'
        }
        /// <summary>
        /// Test the property 'BookEffectiveDateOfChangeId'
        /// </summary>
        [Fact]
        public void BookEffectiveDateOfChangeIdTest()
        {
            // TODO unit test for the property 'BookEffectiveDateOfChangeId'
        }

    }

}
