/* 
 * Xero Assets API
 *
 * This is the Xero Assets API
 *
 * The version of the OpenAPI document: 2.8.2
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Xero.NetStandard.OAuth2.Api;
using Xero.NetStandard.OAuth2.Model.Asset;
using Xero.NetStandard.OAuth2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Xero.NetStandard.OAuth2.Test.Model.Asset
{
    /// <summary>
    ///  Class for testing BookDepreciationDetail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BookDepreciationDetailTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BookDepreciationDetail
        //private BookDepreciationDetail instance;

        public BookDepreciationDetailTests()
        {
            // TODO uncomment below to create an instance of BookDepreciationDetail
            //instance = new BookDepreciationDetail();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BookDepreciationDetail
        /// </summary>
        [Fact]
        public void BookDepreciationDetailInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BookDepreciationDetail
            //Assert.IsInstanceOfType<BookDepreciationDetail> (instance, "variable 'instance' is a BookDepreciationDetail");
        }


        /// <summary>
        /// Test the property 'CurrentCapitalGain'
        /// </summary>
        [Fact]
        public void CurrentCapitalGainTest()
        {
            // TODO unit test for the property 'CurrentCapitalGain'
        }
        /// <summary>
        /// Test the property 'CurrentGainLoss'
        /// </summary>
        [Fact]
        public void CurrentGainLossTest()
        {
            // TODO unit test for the property 'CurrentGainLoss'
        }
        /// <summary>
        /// Test the property 'DepreciationStartDate'
        /// </summary>
        [Fact]
        public void DepreciationStartDateTest()
        {
            // TODO unit test for the property 'DepreciationStartDate'
        }
        /// <summary>
        /// Test the property 'CostLimit'
        /// </summary>
        [Fact]
        public void CostLimitTest()
        {
            // TODO unit test for the property 'CostLimit'
        }
        /// <summary>
        /// Test the property 'ResidualValue'
        /// </summary>
        [Fact]
        public void ResidualValueTest()
        {
            // TODO unit test for the property 'ResidualValue'
        }
        /// <summary>
        /// Test the property 'PriorAccumDepreciationAmount'
        /// </summary>
        [Fact]
        public void PriorAccumDepreciationAmountTest()
        {
            // TODO unit test for the property 'PriorAccumDepreciationAmount'
        }
        /// <summary>
        /// Test the property 'CurrentAccumDepreciationAmount'
        /// </summary>
        [Fact]
        public void CurrentAccumDepreciationAmountTest()
        {
            // TODO unit test for the property 'CurrentAccumDepreciationAmount'
        }

    }

}
