/* 
 * Xero Assets API
 *
 * This is the Xero Assets API
 *
 * The version of the OpenAPI document: 2.8.2
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Xero.NetStandard.OAuth2.Api;
using Xero.NetStandard.OAuth2.Model.Asset;
using Xero.NetStandard.OAuth2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Xero.NetStandard.OAuth2.Test.Model.Asset
{
    /// <summary>
    ///  Class for testing FieldValidationErrorsElement
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FieldValidationErrorsElementTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FieldValidationErrorsElement
        //private FieldValidationErrorsElement instance;

        public FieldValidationErrorsElementTests()
        {
            // TODO uncomment below to create an instance of FieldValidationErrorsElement
            //instance = new FieldValidationErrorsElement();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FieldValidationErrorsElement
        /// </summary>
        [Fact]
        public void FieldValidationErrorsElementInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FieldValidationErrorsElement
            //Assert.IsInstanceOfType<FieldValidationErrorsElement> (instance, "variable 'instance' is a FieldValidationErrorsElement");
        }


        /// <summary>
        /// Test the property 'FieldName'
        /// </summary>
        [Fact]
        public void FieldNameTest()
        {
            // TODO unit test for the property 'FieldName'
        }
        /// <summary>
        /// Test the property 'ValueProvided'
        /// </summary>
        [Fact]
        public void ValueProvidedTest()
        {
            // TODO unit test for the property 'ValueProvided'
        }
        /// <summary>
        /// Test the property 'LocalisedMessage'
        /// </summary>
        [Fact]
        public void LocalisedMessageTest()
        {
            // TODO unit test for the property 'LocalisedMessage'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Detail'
        /// </summary>
        [Fact]
        public void DetailTest()
        {
            // TODO unit test for the property 'Detail'
        }

    }

}
