/* 
 * Xero Assets API
 *
 * This is the Xero Assets API
 *
 * The version of the OpenAPI document: 2.8.2
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Xero.NetStandard.OAuth2.Api;
using Xero.NetStandard.OAuth2.Model.Asset;
using Xero.NetStandard.OAuth2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Xero.NetStandard.OAuth2.Test.Model.Asset
{
    /// <summary>
    ///  Class for testing ResourceValidationErrorsElement
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResourceValidationErrorsElementTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ResourceValidationErrorsElement
        //private ResourceValidationErrorsElement instance;

        public ResourceValidationErrorsElementTests()
        {
            // TODO uncomment below to create an instance of ResourceValidationErrorsElement
            //instance = new ResourceValidationErrorsElement();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ResourceValidationErrorsElement
        /// </summary>
        [Fact]
        public void ResourceValidationErrorsElementInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ResourceValidationErrorsElement
            //Assert.IsInstanceOfType<ResourceValidationErrorsElement> (instance, "variable 'instance' is a ResourceValidationErrorsElement");
        }


        /// <summary>
        /// Test the property 'ResourceName'
        /// </summary>
        [Fact]
        public void ResourceNameTest()
        {
            // TODO unit test for the property 'ResourceName'
        }
        /// <summary>
        /// Test the property 'LocalisedMessage'
        /// </summary>
        [Fact]
        public void LocalisedMessageTest()
        {
            // TODO unit test for the property 'LocalisedMessage'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Detail'
        /// </summary>
        [Fact]
        public void DetailTest()
        {
            // TODO unit test for the property 'Detail'
        }

    }

}
