/* 
 * Xero Assets API
 *
 * This is the Xero Assets API
 *
 * The version of the OpenAPI document: 2.8.2
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Xero.NetStandard.OAuth2.Api;
using Xero.NetStandard.OAuth2.Model.Asset;
using Xero.NetStandard.OAuth2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Xero.NetStandard.OAuth2.Test.Model.Asset
{
    /// <summary>
    ///  Class for testing Setting
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SettingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Setting
        //private Setting instance;

        public SettingTests()
        {
            // TODO uncomment below to create an instance of Setting
            //instance = new Setting();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Setting
        /// </summary>
        [Fact]
        public void SettingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Setting
            //Assert.IsInstanceOfType<Setting> (instance, "variable 'instance' is a Setting");
        }


        /// <summary>
        /// Test the property 'AssetNumberPrefix'
        /// </summary>
        [Fact]
        public void AssetNumberPrefixTest()
        {
            // TODO unit test for the property 'AssetNumberPrefix'
        }
        /// <summary>
        /// Test the property 'AssetNumberSequence'
        /// </summary>
        [Fact]
        public void AssetNumberSequenceTest()
        {
            // TODO unit test for the property 'AssetNumberSequence'
        }
        /// <summary>
        /// Test the property 'AssetStartDate'
        /// </summary>
        [Fact]
        public void AssetStartDateTest()
        {
            // TODO unit test for the property 'AssetStartDate'
        }
        /// <summary>
        /// Test the property 'LastDepreciationDate'
        /// </summary>
        [Fact]
        public void LastDepreciationDateTest()
        {
            // TODO unit test for the property 'LastDepreciationDate'
        }
        /// <summary>
        /// Test the property 'DefaultGainOnDisposalAccountId'
        /// </summary>
        [Fact]
        public void DefaultGainOnDisposalAccountIdTest()
        {
            // TODO unit test for the property 'DefaultGainOnDisposalAccountId'
        }
        /// <summary>
        /// Test the property 'DefaultLossOnDisposalAccountId'
        /// </summary>
        [Fact]
        public void DefaultLossOnDisposalAccountIdTest()
        {
            // TODO unit test for the property 'DefaultLossOnDisposalAccountId'
        }
        /// <summary>
        /// Test the property 'DefaultCapitalGainOnDisposalAccountId'
        /// </summary>
        [Fact]
        public void DefaultCapitalGainOnDisposalAccountIdTest()
        {
            // TODO unit test for the property 'DefaultCapitalGainOnDisposalAccountId'
        }
        /// <summary>
        /// Test the property 'OptInForTax'
        /// </summary>
        [Fact]
        public void OptInForTaxTest()
        {
            // TODO unit test for the property 'OptInForTax'
        }

    }

}
